#!/usr/bin/env bash
# makes my setup for 2 monitors

connected_monitors=$(xrandr | grep " connected" | awk '{print $1}')
monitor_count=$(echo "$connected_monitors" | wc -l)

if [ "$monitor_count" -eq 2 ]; then
    primary_monitor=$(echo "$connected_monitors" | head -n 1)
    secondary_monitor=$(echo "$connected_monitors" | tail -n 1)
    xrandr --auto
    xrandr --output "$secondary_monitor" --left-of "$primary_monitor"
    for i in {1..5}; do
        # Move workspace to the new monitor
        i3-msg workspace $i > /dev/null 2>&1
        i3-msg move workspace to output $secondary_monitor > /dev/null 2>&1
        i3-msg workspace 2 > /dev/null 2>&1
    done
else
    xrandr --auto
fi
